### ISSUE TITLE
Moment-related build error

### ISSUE THREAD

**Issue by hbjydev** [rocky-linux/rockylinux.org-gatsby#15]
From [Vercel build logs](https://vercel.com/rocky-linux/rockylinux/ogtzy4lhj):

```
12:24:28.497 | Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
-- | --
12:24:28.497 | Arguments:
12:24:28.497 | [0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: January 20, 2020, _f: undefined, _strict: undefined, _locale: [object Object]
12:24:28.497 | Error
12:24:28.497 | at Function.createFromInputFallback (/vercel/workpath0/public/render-page.js:7814:25)
12:24:28.497 | at configFromString (/vercel/workpath0/public/render-page.js:10031:19)
12:24:28.498 | at configFromInput (/vercel/workpath0/public/render-page.js:10472:13)
12:24:28.498 | at prepareConfig (/vercel/workpath0/public/render-page.js:10455:13)
12:24:28.498 | at createFromConfig (/vercel/workpath0/public/render-page.js:10422:44)
12:24:28.498 | at createLocalOrUTC (/vercel/workpath0/public/render-page.js:10516:16)
12:24:28.498 | at createLocal (/vercel/workpath0/public/render-page.js:10520:16)
12:24:28.498 | at hooks (/vercel/workpath0/public/render-page.js:7511:29)
12:24:28.498 | at BlogPost (/vercel/workpath0/public/render-page.js:15533:1413)
12:24:28.499 | at d (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
12:24:28.499 | at $a (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
12:24:28.499 | at a.b.render (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
12:24:28.499 | at a.b.read (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
12:24:28.499 | at renderToString (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
12:24:28.499 | at Module../.cache/static-entry.js.__webpack_exports__.default (/vercel/workpath0/public/render-page.js:642:28)
12:24:28.499 | at /vercel/workpath0/node_modules/gatsby/dist/utils/worker/render-html.js:30:36
12:24:28.500 | Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
12:24:28.500 | Arguments:
12:24:28.500 | [0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: December 09, 2020, _f: undefined, _strict: undefined, _locale: [object Object]
12:24:28.500 | Error
12:24:28.500 | at Function.createFromInputFallback (/vercel/workpath0/public/render-page.js:7814:25)
12:24:28.500 | at configFromString (/vercel/workpath0/public/render-page.js:10031:19)
12:24:28.501 | at configFromInput (/vercel/workpath0/public/render-page.js:10472:13)
12:24:28.501 | at prepareConfig (/vercel/workpath0/public/render-page.js:10455:13)
12:24:28.501 | at createFromConfig (/vercel/workpath0/public/render-page.js:10422:44)
12:24:28.501 | at createLocalOrUTC (/vercel/workpath0/public/render-page.js:10516:16)
12:24:28.501 | at createLocal (/vercel/workpath0/public/render-page.js:10520:16)
12:24:28.501 | at hooks (/vercel/workpath0/public/render-page.js:7511:29)
12:24:28.501 | at BlogPost (/vercel/workpath0/public/render-page.js:15533:1413)
12:24:28.502 | at d (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
12:24:28.502 | at $a (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
12:24:28.502 | at a.b.render (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
12:24:28.502 | at a.b.read (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
12:24:28.502 | at renderToString (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
12:24:28.502 | at Module../.cache/static-entry.js.__webpack_exports__.default (/vercel/workpath0/public/render-page.js:642:28)
12:24:28.502 | at /vercel/workpath0/node_modules/gatsby/dist/utils/worker/render-html.js:30:36
```

Note that it doesn't break the build, but we should still probably try and tidy this up regardless.

**Comment by FoggyMtnDrifter** [comment]
I will work on this now, thanks for the heads up!

**Comment by FoggyMtnDrifter** [comment]
8845d905d84756f884e4aef24a5330a9cf94c76a addresses eslint warnings and this warning, turns out `moment` wasn't even necessary in this case.

**Comment by hbjydev** [comment]
Do you wanna PR that through?

**Comment by FoggyMtnDrifter** [comment]
Sure thing!
